### PR TITLE
v0.12 Release

### PR DESCRIPTION
**Pull request by JWCook**
See all issues and PRs included here: https://github.com/niconoe/pyinaturalist/milestone/3?closed=1
See summary of changes here: https://github.com/niconoe/pyinaturalist/blob/dev/HISTORY.md#012-est-2021-02

### CODE REVIEW

**Comment by JWCook** [comment]
Almost done with this. Planning to release within the next week or two if nothing else comes up.

**Comment by JWCook** [comment]
@willkuhn Fyi, your recent changes are now in the latest stable release. I was also able to make use of the functions you added in a couple of the examples here: https://github.com/niconoe/pyinaturalist/tree/dev/examples 
Thanks again for the contributions!

**Comment by JWCook** [comment]
@niconoe Just an fyi that 0.12 is now out! 🎉

**Comment by niconoe** [comment]
That's great, phenomenal work and it seems the package is taking off (based on the number of stars, discussion on the iNat forum, ...)! Thanks again, I still plan/hope to come back helping you at some point.

**Pull request merged**
