### PR TITLE
Add support to posts API endpoints

### PR DESCRIPTION
**Pull request by eduramirezh**
This change adds support to fetching journal posts through the [GET Posts endpoint](https://api.inaturalist.org/v1/docs/#!/Posts/get_posts)

### CODE REVIEW

**Comment by JWCook** [comment]
Thanks for the PR, this looks great!

**Comment by eduramirezh** [comment]
Thank YOU for your awesome work in this project @JWCook!

**Comment by JWCook** [comment]
I'm glad you've found it useful! I'm curious, what kind of project are you working on that uses journal posts?

**Comment by eduramirezh** [comment]
I find myself using a combination of eBird, iNaturalist and a GPS tracker when “in the field”, so I'm working on a way to combine all this into a journal. I ran into iNaturalist's journal posts and I figured I could use that data as well.

**Comment by JWCook** [comment]
That sounds really cool! It might be worth making a post about that on the iNat forums and/or Discord to see if any other users have done something similar.

Off the top of my head, [this forum thread](https://forum.inaturalist.org/t/how-to-efficiently-revisit-locations-of-numerous-observations/17969) and [this script](https://github.com/JWCook/pyinaturalist-convert/blob/main/pyinaturalist_convert/gpx.py) for converting observations to GPX may or may not be relevant. It may also be worth checking out the [Dronefly](https://github.com/synrg/dronefly) bot, which uses both iNat and eBird taxonomy data.

**Comment by JWCook** [comment]
Also, your changes are now in the latest stable release (`0.14.1`).

**Comment by eduramirezh** [comment]
Thanks for those links, I think they could be very helpful for my project! For now, I'm working on this more as a personal thing, but if it becomes something that could be useful for other people I'll definitely share it on the iNat forum. It's on a VERY early stage, though.

**Pull request merged**
