### PR TITLE
added /observations/observers and /observations/identifiers endpoints

### PR DESCRIPTION
**Pull request by willkuhn**

### CODE REVIEW

**Comment by JWCook** [comment]
Almost there! Just a couple more things:
* It looks like you may have merged `upstream/dev` into your branch instead of rebasing on top of it. I can fix that after merging this, if you've had enough fun with the command line for now. Or you could try `git rebase upstream/dev`.
* We don't need the `get_all_*` functions at this point. Those endpoints support a page size of up to 500, and since we can only get 500 results right now, `get_observation_observers()` will return the same results as `get_all_observation_observers()`. Same for identifiers.

Otherwise the changes look good! Thanks for putting this together.

**Comment by JWCook** [comment]
One more (completely optional) tip: if you get tired of committing something and then having one of the code analysis steps  (`black`, `mypy`, etc.) complain at you when the CI job runs, there's an option to have all those checks run locally every time you make a commit. I recently added config to set this up, with [instructions here](https://pyinaturalist.readthedocs.io/en/latest/contributing.html#pre-commit-hooks).

Setup commands:
```bash
pip install --upgrade  --editable ".[dev]"          # Make sure you have the all the optional 'dev' packages
pre-commit install --config .github/pre-commit.yml  # Install a git pre-commit hook to run code analysis tools
```

**Comment by willkuhn** [comment]
Well, I removed the ``get_all_*`` functions and their tests and attempted to ``git rebase upstream/dev`` and find myself in conflict hell. I think I'm making it worse and I want to punch a wall, so I'm going to let you fix it after merge if you would. Sorry about that.

Thanks for the pre-commit suggestion. I'll do that

**Comment by JWCook** [comment]
No worries. Merged and rebased!

**Pull request merged**
