### PR TITLE
Add taxa endpoints

### PR DESCRIPTION
**Pull request by JWCook**
### New endpoints
This PR adds the [`/taxa` endpoints](https://api.inaturalist.org/v1/docs/#!/Taxa/) from the iNaturalist Node API:
* `/taxa`
* `/taxa/{id}`
* `/taxa/autocomplete`

### Rank ranges
In addition to the parameters exposed by  `/taxa`, this also adds support for searching taxa by a range of ranks, via `min_rank` and/or `max_rank`. This is intended to match the search features in the web UI:
Annotation 2020-04-23 131251

### Minor documentation, dependency, and config updates
* Add development packages to `[dev]` setuptools extra
   (e.g., for local testing, generating docs, etc. outside of tox environments)
* Add a couple more example commands to docs
* Bump pinned version of `requests-mock` to 1.7.0 for recent feature additions
* Bump pinned version of `pytest` to 4.6.9
  (the last release that still works under python3.4)
* Add `Sphinx` and `sphinx-autodoc-typehints` to `requirements.txt`

### Note on unit tests
`requests_mock` now provides a pytest fixture, which plays more nicely with pytest than the decorator. See:
* https://github.com/pytest-dev/pytest/issues/2749
* https://bugs.launchpad.net/requests-mock/+bug/1714756
* https://github.com/jamielennox/requests-mock/pull/51

### Checklist
- [x] Issue: #12
- [x] Docstrings (that render correctly in Sphinx)
- [x] Unit tests
- [x] Sample data
- [x] Type annotations
- [x] Black formatting

Please let me know if there is anything you'd like me to change in this PR, or if you have additional contribution guidelines to follow that I missed.

### CODE REVIEW

**Comment by niconoe** [comment]
Wow, thanks a lot for the contribution @JWCook! 

Sorry for my lack of responsiveness, I've been quite busy recently but I'll have a lok very soon and will let you know!

**Comment by JWCook** [comment]
@niconoe No worries, take your time!

It looks like I have a couple compatibility issues to fix for the older interpreters. I'll get those sorted out, but would you consider dropping support for Python <= 3.5 at some point in the future? [Python 3.4 reached EOL in March 2019](https://devguide.python.org/devcycle/#end-of-life-branches), and [3.5 will reach EOL this September](https://devguide.python.org/#status-of-python-branches).

**Comment by niconoe** [comment]
@JWCook: about Python compatibility: I don't have a very strong opinion on this, I'd say supporting 3.4 (the most recent deprecated one) is nice for now, but not forever...

If we keep this logic, it could make sense to only support 3.5+ after September (once 3.5 is itself unsupported). Do you think that would be reasonable?

**Comment by JWCook** [comment]
@niconoe Sure, sounds reasonable.

Also, I rebased onto master once more. I'm done messing with this PR now; I'll likely have another one for you to review soon, though.

**Pull request merged**
